import { test, expect } from "bun:test";
import { mkdtemp, readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { startBroker, call } from "../src/ipc";
import { launchChrome } from "../src/chrome";
import { createWorkspaceDirectory } from "../src/workspace-storage";

(process.env.ORBIT_TEST_NATIVE === "1" ? test : test.skip)("viewer wheel controls only a paused native session", async () => {
  const root = await mkdtemp("/tmp/orbit-viewer-scroll-");
  const broker = await startBroker();
  const browser = await launchChrome(await createWorkspaceDirectory("viewer-scroll"));
  try {
    const session = await call(broker.socket, "session.create", { backend: "fedora" }) as { sessionId: string };
    const file = join(root, "state.json");
    await call(broker.socket, "session.act", { ...session, requestId: "launch", action: { type: "launch", toolkit: "x11", argv: ["/usr/bin/python3", resolve("experiments/fedora-display/scroll-fixture.py"), file] } });
    const vertical = async () => JSON.parse(await readFile(file, "utf8")).vertical as number;
    const { url } = await call(broker.socket, "preview.open") as { url: string };
    const page = browser.page, errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.setViewportSize({ width: 1000, height: 1000 });
    await page.goto(url);
    await page.locator("#frame").waitFor({ state: "visible" });
    expect(await page.title()).toContain("Orbit");
    const box = await page.locator("#frame").boundingBox();
    if (!box) throw new Error("Missing viewer frame");
    const point = { x: box.x + box.width * 0.4, y: box.y + box.height * 0.4 };
    await page.mouse.move(point.x, point.y);
    await page.mouse.wheel(0, 300);
    await Bun.sleep(300);
    expect(await vertical()).toBe(0);
    const input = { type: "scroll", x: 200, y: 200, deltaY: 3 };
    await expect(call(broker.socket, "session.control", { ...session, input })).rejects.toMatchObject({ code: "NOT_PAUSED" });
    await page.locator("#pause").click();
    await page.waitForFunction(() => document.querySelector("#state")?.textContent === "paused");
    await page.locator("#frame").scrollIntoViewIfNeeded();
    const pausedBox = await page.locator("#frame").boundingBox();
    if (!pausedBox) throw new Error("Missing paused frame");
    await page.mouse.move(pausedBox.x + pausedBox.width * 0.4, pausedBox.y + pausedBox.height * 0.4);
    const controls: unknown[] = [];
    page.on("request", request => { const body = request.postDataJSON(); if (body?.method === "session.control") controls.push(body.params.input); });
    await page.mouse.wheel(0, 300);
    for (let i = 0; i < 100 && await vertical() === 0; i++) await Bun.sleep(30);
    expect(await vertical()).toBeGreaterThan(0);
    expect(controls[0]).toMatchObject({ type: "scroll", deltaY: 3 });
    expect(Math.abs((controls[0] as { x: number }).x - 512)).toBeLessThanOrEqual(2);
    expect(Math.abs((controls[0] as { y: number }).y - 320)).toBeLessThanOrEqual(2);
    await page.waitForFunction(() => !document.querySelector<HTMLButtonElement>("#resume")?.disabled);
    await page.mouse.wheel(0, -300);
    for (let i = 0; i < 100 && await vertical() > 0.1; i++) await Bun.sleep(30);
    expect(await vertical()).toBeCloseTo(0, 1);
    await page.locator("#resume").click();
    await page.waitForFunction(() => document.querySelector("#state")?.textContent === "running");
    await page.locator("#frame").hover();
    const count = controls.length;
    await page.mouse.wheel(0, 300);
    await Bun.sleep(300);
    expect(controls.length).toBe(count);
    expect(await vertical()).toBeCloseTo(0, 1);
    expect(errors).toEqual([]);
    await page.screenshot({ path: "output/native-viewer-scroll.png", fullPage: true });
  } finally { await browser.close(); await broker.close(); }
}, 30000);
