import { test, expect } from 'bun:test';
import { mkdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { startBroker, call } from '../src/ipc';
import { Sessions } from '../src/session';
import { BrowserBackend } from '../src/browser';
import { createWorkspaceDirectory } from '../src/workspace-storage';

const fixture = `<!doctype html><html><head><title>Workspace library</title><style>*{box-sizing:border-box}body{margin:0;background:#f5f6f8;color:#20282f;font:16px system-ui}header{padding:26px 40px;background:white;display:flex;justify-content:space-between}main{padding:45px 60px}small{color:#71818e}h1{font-size:34px;letter-spacing:-1px;margin:8px 0}p{color:#687684}.cards{display:flex;gap:18px;margin:32px 0}.card{background:white;border-radius:16px;padding:24px;flex:1}strong{font-size:32px;display:block;margin-top:16px}table{width:100%;background:white;border-radius:16px;padding:20px;text-align:left}th,td{padding:18px;font-size:14px}th{color:#79838f;font-weight:500}.tag{background:#e7f4ec;border-radius:20px;padding:6px 12px;color:#377354}</style></head><body><header><b>Studio / Workspace</b><small>Product team</small></header><main><small>PROJECT OVERVIEW</small><h1>Workspace library</h1><p>A clear view of the work in progress.</p><div class="cards"><div class="card"><small>Active projects</small><strong>12</strong></div><div class="card"><small>In review</small><strong>4</strong></div><div class="card"><small>Completed this week</small><strong>8</strong></div></div><table><tr><th>Project</th><th>Owner</th><th>Status</th></tr><tr><td>Workspace navigation</td><td>Design team</td><td><span class="tag">In review</span></td></tr><tr><td>Account settings</td><td>Product team</td><td>In progress</td></tr><tr><td>Diagnostic reports</td><td>Engineering</td><td>Ready</td></tr></table></main></body></html>`;

test('viewer prioritizes the screen and keeps conversation, sidebar and page navigation distinct', async () => {
  const broker = await startBroker();
  const root = await createWorkspaceDirectory('viewer-layout-qa');
  const viewing = new Sessions(root);
  const server = Bun.serve({hostname:'127.0.0.1',port:0,fetch:() => new Response(fixture,{headers:{'Content-Type':'text/html'}})});
  const shots = process.env.ORBIT_QA_OUTPUT ?? '/tmp/orbit-viewer-layout';
  try {
    const a = await call(broker.socket,'session.create',{backend:'browser',agentName:'Codex',taskName:'Review navigation',conversationName:'Polish the workspace',projectName:'Sbar Orbit'}) as {sessionId:string};
    const b = await call(broker.socket,'session.create',{backend:'browser',agentName:'Hermes',taskName:'Review account settings',conversationName:'Account settings',projectName:'Studio'}) as {sessionId:string};
    expect(a).toMatchObject({conversationName:'Polish the workspace',projectName:'Sbar Orbit'});
    await call(broker.socket,'session.act',{...a,requestId:'navigate',action:{type:'navigate',url:`http://127.0.0.1:${server.port}`}});
    await call(broker.socket,'session.act',{...a,requestId:'tab',action:{type:'open-tab',url:`http://127.0.0.1:${server.port}/settings`}});
    const preview = await call(broker.socket,'preview.open') as {url:string};
    const own = await viewing.dispatch({method:'session.create',params:{backend:'browser',agentName:'Codex',taskName:'Viewer design QA'}}) as {sessionId:string};
    const backend = (viewing as unknown as {sessions:Map<string,{backend:BrowserBackend}>}).sessions.get(own.sessionId)?.backend;
    const page = backend?.context.pages()[0];
    if (!page) throw new Error('Private Orbit page missing');
    const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
    await page.setViewportSize({width:1440,height:1000});
    await page.goto(preview.url,{waitUntil:'domcontentloaded'});
    await page.locator('#frame').waitFor({state:'visible'});
    expect(await page.title()).toBe('Polish the workspace · Sbar Orbit | Orbit');
    expect(await page.locator('#conversation-tabs button').count()).toBe(2);
    expect(await page.locator('#conversation-tabs').textContent()).toContain('Studio');
    const normal = await page.locator('#frame').boundingBox();
    if (!normal) throw new Error('Frame missing');
    expect(normal.height).toBeGreaterThan(600);
    await page.getByRole('button',{name:'Hide sidebar',exact:true}).click();
    expect(await page.locator('#sidebar').isVisible()).toBe(false);
    await page.reload({waitUntil:'domcontentloaded'});
    expect(await page.locator('#sidebar').isVisible()).toBe(false);
    await page.getByRole('button',{name:'Show sidebar',exact:true}).click();
    await page.locator('#frame').waitFor({state:'visible'});
    await page.getByRole('button',{name:'Focus view',exact:true}).click();
    expect(await page.locator('#sidebar').isVisible()).toBe(false);
    const focused = await page.locator('#frame').boundingBox();
    expect(focused?.width ?? 0).toBeGreaterThan(normal.width);
    const surface = await page.locator('.surface').boundingBox();
    expect(Math.abs((surface?.width ?? 0)-(focused?.width ?? 1))).toBeLessThan(1);
    await mkdir(shots,{recursive:true});
    await page.screenshot({path:join(shots,'focus.png'),fullPage:true});
    await page.keyboard.press('Escape');
    expect(await page.locator('#expand').getAttribute('aria-pressed')).toBe('false');
    expect(await page.locator('#sidebar').isVisible()).toBe(true);
    await page.getByRole('button',{name:'Enter fullscreen',exact:true}).click();
    await page.waitForFunction(()=>!!document.fullscreenElement);
    await page.getByRole('button',{name:'Exit fullscreen',exact:true}).click();
    await page.waitForFunction(()=>!document.fullscreenElement);
    await page.keyboard.press('Escape');
    await page.locator('#conversation-tabs button').nth(1).click();
    await page.waitForFunction(()=>document.title.startsWith('Account settings'));
    expect(await page.locator('#project-name').textContent()).toBe('Studio');
    await page.locator('#conversation-tabs button').nth(0).click();
    await page.waitForFunction(()=>document.title.startsWith('Polish the workspace'));
    await page.locator('#tabs button').nth(1).waitFor({state:'visible'});
    expect(await page.locator('#tabs button').nth(0).isDisabled()).toBe(true);
    await page.getByRole('button',{name:'Take over',exact:true}).click();
    await page.locator('#tabs button').nth(0).click();
    await page.waitForFunction(()=>document.querySelector('#tabs button')?.getAttribute('aria-selected')==='true');
    const presence = await call(broker.socket,'session.presence',a) as {pageIndex:number};
    expect(presence.pageIndex).toBe(1);
    await page.getByRole('button',{name:'Hand back',exact:true}).click();
    await page.locator('#manual summary').click();
    expect(await page.locator('#frame').evaluate(element => element.getBoundingClientRect().bottom <= innerHeight)).toBe(true);
    await page.screenshot({path:join(shots,'desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.locator('#sidebar').waitFor({state:'hidden'});
    expect(await page.locator('#sidebar').isVisible()).toBe(false);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.screenshot({path:join(shots,'mobile.png'),fullPage:true});
    await page.getByRole('button',{name:'Show sidebar',exact:true}).click();
    expect(await page.locator('#sidebar').isVisible()).toBe(true);
    await page.keyboard.press('Escape');
    expect(await page.locator('#sidebar').isVisible()).toBe(false);
    expect(errors).toEqual([]);
  } finally {await viewing.close();await broker.close();server.stop(true);await rm(root,{recursive:true,force:true});}
},60000);
